### ISSUE TITLE
Functional and component specification feedback

### ISSUE THREAD

**Issue by elmisback** [gabewiss/CSE_583_COVID_MANDATES#1]
* Functional
    * https://github.com/gabewiss/covid/blob/main/docs/SoftwareDesign.pdf
    * Problem being addressed
        * Map/charts correlating COVID 19 mandate implementation and case counts
    * Data sources, data structure
        * COVID 19 county case counts + preventive mandates by county
    * Users: domain, skills, programming experience
        * Policymakers implementing new measures
        * Citizens
    * At least 2 use cases
        * "I want to see the effectiveness of mandates"
        * "I want to compare case rates by state/county"
* Component
    * https://github.com/gabewiss/covid/blob/main/docs/CSE583_ComponentDiagram.pdf
    * 3+ software components: what it does, inputs it requires, and outputs it provides.
        * I think this diagram does a pretty good job of explaining the parts of your application and the path of data through the parts. However, the diagram doesn't specify what is moving from one part to another. You should write out the inputs and outputs of the parts to make sure the specification for each part is clear.

**Comment by gabewiss** [comment]
Hi Edward,

Are the bulleted squares suggestions on how to better answer the functional and component sections?

Gabe

**Comment by elmisback** [comment]
Hi Gabe, I was taking notes as well as making suggestions. So I think your functional spec is fine, but the component spec could use just a bit more work to make sure the inputs and outputs for the parts are clear.
