### ISSUE TITLE
travis libraries to remove

### ISSUE THREAD

**Issue by kbalmes** [gabewiss/CSE_583_COVID_MANDATES#7]
Our group had a similar issue with not being able to build on travis at first. Dave told us to "remove appnope, all lines that begin with lib and mkl. zlib, blas, backports* should also go." It then started to pass on travis so maybe this might help out you all too.

**Comment by gabewiss** [comment]
I removed the ones you suggested and it passed! Thanks so much. I think we have more to add (have to check the packages in the environment), but I so appreciate you giving me the list of additional packages

**Comment by jhan326** [comment]
@kbalmes 
That's really helpful! 
We just removed mkl, and it seems to be working at this point, but we can re-visit when we encounter more problems.

**Comment by kbalmes** [comment]
Awesome! Glad it worked out.
